package pro.batmin.connect

import io.nekohasekai.libbox.PlatformInterface

/**
 * Android adapter between libbox and BatminVpnService.
 *
 * First compilation intentionally leaves PlatformInterface methods
 * unimplemented. Kotlin compiler will give us the exact contract
 * generated by the pinned libbox.aar.
 */
class LibboxPlatform(
    private val vpnService: BatminVpnService
) : PlatformInterface
